Repository GSG-G10/REMAN, pull requests merged in 2021-10, with the labels that each got.

#28 connection file with edit script on packageJson
  package.json
  server/database/config/connection.js
Labels: Awaiting Review

#26 Build the navbar and header common components
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/assets/logo.png
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/components/common/NavTab/Logo.jsx
  client/src/components/common/NavTab/Nav.jsx
  client/src/components/common/NavTab/Navbar.css
  client/src/components/common/NavTab/UserArea.jsx
  client/src/components/common/NavTab/index.jsx
  client/src/components/common/index.js
  client/src/index.css
Labels: Changes Requested

#27 set up database and insert fake data
  server/database/builds/fakeData.sql
  server/database/builds/init.sql
Labels: Awaiting Review

#38 Fix syntax of database
  server/database/builds/fakeData.sql
  server/database/builds/init.sql
Labels: Awaiting Review

#30 Build signup page
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/signup.png
  client/src/components/SignUp/SignUpForm.jsx
  client/src/components/SignUp/Social.jsx
  client/src/components/SignUp/index.jsx
  client/src/components/SignUp/style.css
  client/src/components/index.jsx
  client/src/pages/Home.jsx
  package-lock.json
  package.json
Labels: Awaiting Review

#41 get filtered products with server side pagination
  package.json
  server/controllers/index.js
  server/controllers/products/getProducts.js
  server/controllers/products/index.js
  server/database/builds/fakeData.sql
  server/database/builds/init.sql
  server/database/queries/index.js
  server/database/queries/products/getProductsQuery.js
  server/database/queries/products/index.js
  server/routes/index.js
Labels: Awaiting Review

#42 Resposive design Navbar&Header
  client/src/components/Header/style.css
  client/src/components/SignUp/style.css
  client/src/components/common/NavTab/Nav.jsx
  client/src/components/common/NavTab/Navbar.css
Labels: Done

#47 get one product data by id
  server/controllers/products/getProductDataController.js
  server/controllers/products/index.js
  server/database/queries/products/getProductDataQuery.js
  server/database/queries/products/getProductsQuery.js
  server/database/queries/products/index.js
  server/routes/index.js
Labels: Awaiting Review, Backend

#45 Login form
  client/src/App.jsx
  client/src/assets/login.gif
  client/src/components/Login/LoginForm.jsx
  client/src/components/Login/index.jsx
  client/src/components/Login/login.css
Labels: Awaiting Review

#40 header section
  client/src/Home/Header.jsx
  client/src/Home/header.css
  client/src/components/Footer/Footer.jsx
  client/src/components/common/Img.jsx
Labels: Awaiting Review

#48 show slider on page
  client/src/Slider/Slider.jsx
  client/src/Slider/header.css
  client/src/pages/Home.jsx
Labels: Awaiting Review

#49 Filter products component
  client/package-lock.json
  client/package.json
  client/src/Slider/header.css
  client/src/components/FilterProducts/Categories.jsx
  client/src/components/FilterProducts/FilterButton.jsx
  client/src/components/FilterProducts/MaxPrice.jsx
  client/src/components/FilterProducts/MinPrice.jsx
  client/src/components/FilterProducts/Name.jsx
  client/src/components/FilterProducts/RateStars.jsx
  client/src/components/FilterProducts/index.jsx
  client/src/components/FilterProducts/style.css
  client/src/components/Main/index.jsx
  client/src/components/Main/style.css
  client/src/components/index.jsx
  client/src/pages/Home.jsx
Labels: Awaiting Review, Done, Ready to merge

#35 create card component and section best seller on main page
  client/package-lock.json
  client/src/App.jsx
  client/src/Home.jsx
  client/src/components/BestSellerSection.jsx
  client/src/components/Card/ContentCard.jsx
  client/src/components/Card/LikeBtn.jsx
  client/src/components/Card/ProductCard.jsx
  client/src/components/Card/PurchaseBtn.jsx
  client/src/components/Card/card.css
  client/src/components/Card/purchaseRequest.js
  client/src/home.css
  client/src/index.css
Labels: Awaiting Review, Frontend

#43 signup
  .gitignore
  package-lock.json
  server/controllers/getProductsByCId.js
  server/controllers/index.js
  server/controllers/register.js
  server/database/config/connection.js
  server/database/queries/Products/getProductByCgId.js
  server/database/queries/Products/index.js
  server/database/queries/User/AddUser.js
  server/database/queries/User/checkUserByEmail.js
  server/database/queries/User/index.js
  server/database/queries/index.js
  server/routes/index.js
  server/utils/validations/index.js
  server/utils/validations/regSchema.js
Labels: Changes Requested

#57 receive data about products from api
  client/package.json
  client/src/App.jsx
  client/src/Home.jsx
  client/src/Utils/DataContext.js
  client/src/components/BestSellerSection.jsx
  client/src/components/Card/ContentCard.jsx
  client/src/components/Card/LikeBtn.jsx
  client/src/components/Card/ProductCard.jsx
  client/src/components/Card/PurchaseBtn.jsx
  client/src/components/Card/card.css
  client/src/components/FilterProducts/index.jsx
  client/src/components/Main/index.jsx
  client/src/components/Main/style.css
  client/src/home.css
  client/src/index.css
  client/src/pages/Home.jsx
Labels: Done, Frontend

#58 fix-bugs
  client/package-lock.json
  package-lock.json
  package.json
  server/controllers/register.js
  server/database/queries/Products/index.js
  server/database/queries/index.js
  server/database/queries/products/getProductByCgId.js
  server/database/queries/products/index.js
Labels: Awaiting Review

#53 Build the dashboard for admin control as front-end
  client/src/App.jsx
  client/src/components/Dashboard/NewProduct.jsx
  client/src/components/Dashboard/index.jsx
  client/src/components/Dashboard/style.css
  package-lock.json
Labels: Awaiting Review, Done, Frontend, Ready to merge

#59 Deployment
  package.json
  server/app.js
  server/controllers/getProductsByCId.js
  server/controllers/register.js
  server/routes/index.js
Labels: Awaiting Review
